### ISSUE TITLE
HTTP Error 401.2 - Unauthorized You are not authorized to view this page due to invalid authentication headers. while enabling windows authentication 

### ISSUE THREAD

**Issue by shakimran** [webgio/Rotativa#100]
Hi,
I am getting this error: HTTP Error 401.2 - Unauthorized You are not authorized to view this page due to invalid authentication headers. while enabling windows authentication. All other pages works fine.

**Comment by joshyates1980** [comment]
I have been troubleshooting this issue.  My web app uses windows authentication.  It's too bad the MVC attribute  [AllowAnonymous] doesn't work.

**Comment by ojpbay** [comment]
I'm facing a similar issue? Did you manage to get round this?

**Comment by shakimran** [comment]
Nop

On Mon, Oct 26, 2015 at 10:45 PM, Oliver Baylis <notifications@github.com>
wrote:

> I'm facing a similar issue? Did you manage to get round this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webgio/Rotativa/issues/100#issuecomment-151204947>.
>



-- 
*Shak Mohammad Imran*
Sr. Software Programmer
Southtech Limited <http://southtechlimited.com/>

**Comment by jeffvandyke** [comment]
Had a similar issue. If it's a cookie based authentication (which it looks like windows auth is), sending all cookies to the destination should allow access, like so:

return new ActionAsPdf(...) { 
    FileName = "Name.pdf",
    Cookies = Request.Cookies.AllKeys.ToDictionary(k => k, k => Request.Cookies[k].Value)
}

**Comment by bmmathe** [comment]
I had the same issue, downloaded the source and found a PartialViewAsPdf.  Use this instead.  You will have to add your styles in partial since you won't have access to the layout page.

**Comment by webgio** [comment]
Windows authentication is tricky because it requires browser collaboration in sending the right headers. I guess the webkit browser used by wkhtmltopdf doesn't do that. Might be worth investigating if the newest version changed that. it could be tested with the current version on master that is now published as pre-release on nuget.
`Install-Package Rotativa -Pre`

**Comment by peterdew** [comment]
@jeffvandyke sending all cookies didn't work for me. 
(`return new ActionAsPdf("edit",new {id})
                { FileName = $"Mutatie-{id}.pdf",
                  RotativaOptions = new Rotativa.Core.DriverOptions
                  {
                      Cookies = Request.Cookies.AllKeys.ToDictionary(k => k, k => Request.Cookies[k]?.Value)
}};`)
@webgio Installing the latest version with you install-package-suggestion did replace the qtbrowser and the wkhtml.exe files but did not fix the issue. :(

**Comment by KellyDC** [comment]
Just came across this. I'm using the current version yet getting http 401.2. MVC using Windows Authentication. Is this fixed?
