### ISSUE TITLE
Problem generating pdf with https url

### ISSUE THREAD

**Issue by varmanrk** [webgio/Rotativa#102]
HI, 

I am using UrlAsPdf method to generate pdf's and working fine in production server with http url.

We installed SSL and site url browsing with https and when we click on PDF link getting 500 Error and in logs showing below message and anyone please help me to fix this issue

Error: Failed loading page https://www.something.com/.....(sometimes it will work just to ignore this error with --load-error-handling ignore)&#xD;&#xA;"    source="Rotativa"    detail="System.Exception: Error: Failed loading page

**Comment by webgio** [comment]
More then two years passed, hope this was resolved. Perhaps ssl certs were not recognised by the wkhtmltopdf browser. maybe solved using ViewAsPdf or ActionAsPdf...
