### ISSUE TITLE
Footer-font-name Arial Unicode MS

### ISSUE THREAD

**Issue by dsimonubb** [webgio/Rotativa#103]
Hello,
I am trying to display some chinese characters in the footer of a rotativa generated pdf.
The characters are not recognised by the default Arial font, I get question marks instead of the chinese characters, so I tried to change the font: footer-font-name \"Arial Unicode MS\". But the characters are still not displayed correctly, I get the question marks, and if I copy the text from the pdf to a ms word file for example, Word will recognise the font as ArialUnicodeMSStandard. I tried it also with SimSun fonts, but no success, I get the question marks and in Word I get the font SimSunRegular for the font name.
Is there a way to display the chinese characters in the footer ? I am using the customswitches for setting the footer font.
Thank you.

**Comment by furoTmark** [comment]
Hello,
The custom switches are a command line argument for the WkhtmltoPDF.

In order to make it work you have to go to Control panel -> Region and language -> Administrative -> Change system locale... -> in this case I selected Chinese (Simplified, PRC)

**Comment by JemCheung** [comment]
It would be helpful for me. I migrated an MVC4 site from windows server 2008 EN to windows server 2012 CN and the same issue occurred. Thanks for the solution from @furoTmark .
