### ISSUE TITLE
GoJS and Rotativa

### ISSUE THREAD

**Issue by janessaallen** [webgio/Rotativa#107]
Hi, I am using the GoJS library to generate a flowchart. I can create a separate view where the tool renders the flowchart in SVG for printing. However, it will not work with Rotativa and I definitely need to use it to generate the view to PDF. I have been using Rotativa for quite some time with other views, but not with the GoJS library that makes the chart into a SVG diagram. Has anyone had experience using these two tools together?

**Comment by webgio** [comment]
There are a number of issues with SVG rendering with wkhtmltopdf.
e.g. https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1975
