### ISSUE TITLE
ViewAsPdf repeat header on every page (actually override with table record on next page)

### ISSUE THREAD

**Issue by tahiralvi** [webgio/Rotativa#126]
Hi All,
I have used Rotativia with MVC 5, I faced an issue. I have tables to show as pdf, but when any table records exceed to next page, the next page automatically add the table header on first record.

How can i fix this, that the repeating table head stop printing on next page.

**Comment by virlatinus** [comment]
I'm having the same issue. Is there a fix or option to disable the repeating headers?
BTW: This package is awesome!

**Comment by luidne** [comment]
I'm having the same issue.

**Comment by faiz2rock** [comment]
thead, tfoot { display: table-row-group } fix solved the issue for me...

**Comment by tahiralvi** [comment]
@faizalshap  your solution is also working for me. Thanks. I am going to close the Issue.

> thead, tfoot { display: table-row-group } fix solved the issue for me...

This solution also working for me.

**Comment by nafis-sadik** [comment]
> thead, tfoot { display: table-row-group } fix solved the issue for me...

This worked for me too, thanks!

**Comment by abdulrahmannady** [comment]
this worked for me too ty alot

> thead, tfoot { display: table-row-group } fix solved the issue for me...

**Comment by Heena-29** [comment]
this worked form me but not every pdf some pdf is fixed
