### ISSUE TITLE
QPaintDevice: Cannot destroy paint device that is being painted

### ISSUE THREAD

**Issue by ilqar008** [webgio/Rotativa#133]
Hello, i have an app generates pdf from html. But after i added header as in below, it gives such an error as saying that "QPaintDevice: Cannot destroy paint device that is being painted".

Could you help me to solve this issue, please?
Thanks
` 
string customSwitches = string.Format("--load-error-handling ignore --allow {0} --header-html {0}  --header-spacing 4 ", Url.Action("Header", "Print", new { area = "", number }, "http"));

       [AllowAnonymous]
        public ActionResult Header(string number)
        {
            string content = @"<!DOCTYPE html><html><head><style>body {text-align: center; }</style></head><body> № " + number + ", date: " + DateTime.Now.ToShortDateString() + "</body></html>";
            return Content(content);
        }`

**Comment by ilqar008** [comment]
I solved the issue by changing the customswitches  as `string customSwitches = string.Format("--header-html {0}  --header-spacing 4 ", " http://localhost:portnumber/Print/Header?number="+number);`

**Comment by glautrou** [comment]
My issue was because the footer returned 404. More details on [this issue](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2033#issuecomment-572440537).

**Comment by glautrou** [comment]
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2033#issuecomment-572440537
