### ISSUE TITLE
Authentication Issue on Rotativa while trying to show Header and Footer on server

### ISSUE THREAD

**Issue by PraveenkUSA** [webgio/Rotativa#139]
Hi,
I have a requirement to show a cshtml view in header and footer while generating PDF. I have implemented it, works fine in local. But on server, it fails to display. I see the issue being a 401 status code unauthorized access to the action methods.

My Custom switch:- 
string customswitch = string.Format("--allow {0} --footer-html {0} --allow {1} --header-html {1}",
                    Url.Action("Footer", "Home", new { area = "" }, "http"), Url.Action("Header", "Home", new { area = "" }, "http"));

My Action Methods:-

```
    [AllowAnonymous]
    public ActionResult Footer()
    {
        return View();
    }

    [AllowAnonymous]
    public ActionResult Header()
    {          
        return View();
    }
```

Even after giving the AllowAnonymous its still failing. I'm using windows authentication on IIS. When I enable Anonymous authentication (which I don't want to), I can see header and footer on server. 
Please suggest me a workaround to this issue, so that my pdf generates with header and footer on server after deployment.

**Comment by faiz2rock** [comment]
does your controller have Authorize annotation? If it is then try to remove that and test.

**Comment by webgio** [comment]
Windows auth is not really supported. Perhaps it can work if the ViewAsPdf doesn't request external assets (images, css etc).
