### ISSUE TITLE
Can't put html in the footer?

### ISSUE THREAD

**Issue by toadicusrex** [webgio/Rotativa#150]
I have a simple footer on the bottom of a pdf.  If I add it to the bottom of the page like so:

`string switches = String.Format("--print-media-type --allow {0} --footer-html {0}", Url.Action("PrintFooter", "Admin", new { area = "" }, "http"));`

it works just fine... so long as there are no HTML tags in the view for the PrintFooter action.  As soon as I add a bold or something like that, it blows up.  I actually have to add an image because of contractual arrangements... I haven't tried the header yet, but I'm imagining it's the same?  

Help?  Please?

**Comment by toadicusrex** [comment]
Yeah, same for the header.  Sad face.

**Comment by CosX** [comment]
I think you have to declare a doctype for your footer. https://github.com/wkhtmltopdf/wkhtmltopdf/issues/46

**Comment by toadicusrex** [comment]
If that works, you are my best friend for this week.  I will give it a
shot.  Thank you for finding that for me; for some reason I fail at
searching apparently.

**Comment by toadicusrex** [comment]
CosX, you are my best friend for the week.  Thank you so much - I assumed it was something small, and it certainly was.  This project is for a small religious school and they are really excited to finally get their headers and footers on their transcripts finally!

Thank you so much!

**Comment by hbcondo** [comment]
I think this issue can be closed now. I added `<!DOCTYPE html>` to the very top of my HTML page and now  the header / footer renders well within the PDF.
