### ISSUE TITLE
problem on different dpi setting

### ISSUE THREAD

**Issue by yoyoys** [webgio/Rotativa#164]
If i change windows(server)'s dpi setting to 125%(dpi 120), 
the pdf will leave big blank area on right and bottom.

It's wkhtmltopdf 0.12.2's bug, i just replace to 0.12.4, and works fine. #165

**Comment by yoyoys** [comment]
#165

**Comment by webgio** [comment]
I'll have a look at the pull request soon and test it, thanks.

**Comment by webgio** [comment]
Merged the PR and published a new Pre-release Nuget package (1.7.2-pre)
`install-package Rotativa -Pre`
to test it.
In this version I've also updated .net and MVC versions.
