### ISSUE TITLE
I just want generate pdf, don't download it

### ISSUE THREAD

**Issue by levonyang** [webgio/Rotativa#168]
Hi, I want using this package to generate pdf and save on the server. no need to output it.
How to do it?

and is there a method just generate pdf from html string?

Thanks in advance

**Comment by levonyang** [comment]
and is there a method just using html string to generate pdf?

**Comment by jon-adams** [comment]
Yes. Setup a result (as usual) then call `myPdfResult.BuildFile(this.ControllerContext)` which returns a byte array. You may save the byte array as a file like normal.

**Comment by JValck** [comment]
@jon-adams Is there a possibility to do this without the controller context?

**Comment by jon-adams** [comment]
@JValck I'm not a developer on the project—I'm not sure 100%. But I think the point is to pass it all through the MVC pipeline to get the view rendered out so you don't have to do any extra work on separate view rendering... So yeah, I think you pretty much have to use a controller context for all that.
