### ISSUE TITLE
Rotativa.NetCore 1.0.4 not working with core sdk 2.0.

### ISSUE THREAD

**Issue by usfnoor84** [webgio/Rotativa#173]
I am trying to convert mvc core 2.0 view to pdf with rotativa.netcore 1.0.4. But it through an exception as
 
`TypeLoadException: Could not load type 'Microsoft.AspNetCore.Builder.CookieAuthenticationOptions' from assembly 'Microsoft.AspNetCore.Authentication.Cookies, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.`

my code,

```
public ActionResult Index()
        {
            return View();
        }

        public ActionResult PrintIndex()
        {
            return new ActionAsPdf("Index");
        }
```

**Comment by m8kwr** [comment]
Get original source, and make these changes, worked for me...

[Link](https://github.com/aaxelm/Rotativa.NetCore/pull/1/files?diff=split#diff-28c6d2d2d01879434335cb9c7382b682)

**Comment by saineshwar** [comment]
@m8kwr sir can you show what changes have u made such that we can use it

**Comment by webgio** [comment]
I just published Rotativa.AspNetCore. Please let me know if it works for you.
[Rotativa.AspNetCore](https://github.com/webgio/Rotativa.AspNetCore)
