### ISSUE TITLE
wkhtmltopdf has GNU license.  Does this affect Rotativa's license?

### ISSUE THREAD

**Issue by cgvisions** [webgio/Rotativa#176]
Rotativa is licensed under MIT, but wkhtmltopdf is GNU Lesser General Public License v3.0

https://github.com/wkhtmltopdf/wkhtmltopdf/blob/master/LICENSE

If I were to use this in my application, would their GNU override Rotativa's MIT, and therefor my commercial application?

**Comment by webgio** [comment]
No, Rotativa doesn't use any wkhtmtopdf code. It just runs the executable.

**Comment by cgvisions** [comment]
Thanks.

Then, just to be clear, by just running the executable, it doesn't fall under the GNU license and our app would be ok?

**Comment by webgio** [comment]
Exactly. License applies to including/referencing code, not to running executables.

**Comment by cgvisions** [comment]
Appreciate the quick response!

**Comment by saineshwar** [comment]
Close this Issue if completed
