### ISSUE TITLE
Rotativa 1.7.3 has issue when we install from nuget it does not add refernce of its dll 

### ISSUE THREAD

**Issue by saineshwar** [webgio/Rotativa#177]
I have installed latest version of Rotativa package to my project which has .Net framework 4.5 (MVC). 

After Installing it was not having any reference .dll of Rotativa in by project reference and in my bin folder.

It is an issue please have a look on it.

**Comment by ViruX** [comment]
I have the same problem!

**Comment by webgio** [comment]
I've built a package version targeting .net 4.5, could you please test it? It's version 1.7.4-rc.

`Install-Package Rotativa -Version 1.7.4-rc`

Please let me know if it works for you, thanks.

**Comment by saineshwar** [comment]
webgio  sir its working fine now

**Comment by ViruX** [comment]
webgio work fine with 1.7.4-rc version!
thx!

**Comment by pirati02** [comment]
webgio work fine with 1.7.4-rc version!
thx!

**Comment by touhidulfahim** [comment]
Same Problem is in here ... Let Me Check this version .... 👍

**Comment by touhidulfahim** [comment]
Yes 👍 Its Work fine with 1.7.4 🥇

**Comment by AsifKhurshid101** [comment]
Thankyou!! Its Work fine for me...

**Comment by Neto-Santos** [comment]
Thankyou!!! from Brazil, rsrs.

**Comment by zw-gb** [comment]
This did not work for me. For some reason, doing this has actually removed all files as well as not including the references.

**Comment by dlidstrom** [comment]
Isn't it time to release 1.7.4 by now?

**Comment by venkatesh-tpkm** [comment]
> I've built a package version targeting .net 4.5, could you please test it? It's version 1.7.4-rc.
> 
> `Install-Package Rotativa -Version 1.7.4-rc`
> 
> Please let me know if it works for you, thanks.

Thank you!

**Comment by venkatesh-tpkm** [comment]
thank you webgio

**Comment by angelosilva-dev** [comment]
with the .net core 2.1 version it didn't work.

how to solve ?
