### ISSUE TITLE
Return FileStreamResult

### ISSUE THREAD

**Issue by jsiegmund** [webgio/Rotativa#19]
I'm wondering why there is no return type which inherits from FileStreamResult? I want to capture the generated PDF server side in order to attach it to an e-mail. The action itself returns a normal view, not a PDF, but it does send out an e-mail with the PDF attached.

**Comment by Choco516** [comment]
@webgio could you gime an example to save the pdf file to a custom location on the client side not the server side? please.

**Comment by joseluisucan** [comment]
me funciono tu solución @webgio

**Comment by ironman1964** [comment]
Hey @webgio how to use this if the function is called from a webservice and there is no controllerContext available ?

var` binary = pdfResult.BuildPdf(this.ControllerContext);

Thanks,
Joop !

**Comment by augustusle** [comment]
var content = new ViewAsPdf("PDFContent", htmlContent);
var binary = content.BuildPdf(ControllerContext);

@webgio after i call BuildPdf method, all sessions will be lost. Can u help me?
Do you have other method to export pdf from ViewAsPdf?
Thanks!
