### ISSUE TITLE
When reaching BuildFile it gets stuck

### ISSUE THREAD

**Issue by ricardo-bazan** [webgio/Rotativa#203]
When calling BuildFile:
var pdf = new ViewAsPdf("ModelName", model);
var fileBytes = pdf.BuildFile(this.ControllerContext);
It won't advance, just stays there, there's no timeout exception or any error and the request on google chrome just keep saying Pending and it never ends i just left it for 2 hours, still on status Pending.

First time using this tool, any suggestions are appreciated.

**Comment by ricardo-bazan** [comment]
Update:  Rotativa PDF go through all the scripts, one script returned something i couldn't know what it was and somehow it affected the processs Rotativa.BuildFile the solution was making a second way to do what i needed, so i dont have to add the script that corrupted Rotativa.BuildFile, after that it worked normally.

**Comment by molekp** [comment]
Hi

I had same problem with stuck after calling Wkhtml Driver. I figured it out why it get stuck, but anyway I think that Rotativa should have some ability to timeout this process. 

So I've implement it and create PR https://github.com/webgio/Rotativa/pull/229
