### ISSUE TITLE
Blazor compatibility

### ISSUE THREAD

**Issue by softlion** [webgio/Rotativa#212]
Currently,
rotativa contains only mvc actions that can't be converted to a blazor component.

It would be nice to change that.

**Comment by softlion** [comment]
I managed to make it work with Blazor. Ty.

**Comment by jeffersantoss** [comment]
> I managed to make it work with Blazor. Ty.

@softlion ...  How did you make it work with Blazor? Can you show me an example? I'm very interested on that!!

**Comment by softlion** [comment]
I added mvc to the blazer project.
