### ISSUE TITLE
jQuery not running

### ISSUE THREAD

**Issue by JoopStringer** [webgio/Rotativa#215]
I have ASP.NET application succesfully integrated Rotativa.
However I now have a page with jQuery script and it is not executed when using the ViewAsPdf action
Any solutions ? I added "--javascript-delay 10000", no difference.
If I run the page in browser, it's ok and executing jQuery.

Using Rotativa 1.7.3 from NuGet, jQuery 3.1.1

**Comment by webgio** [comment]
Is jquery making Ajax calls?

Il sab 23 mag 2020, 11:05 Joop Stringer <notifications@github.com> ha
scritto:

**Comment by JoopStringer** [comment]
Hi Gio,

No AJAX calls. After some digging I found this post * https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4341
* Override jquery >= 3.3.1 functions because of wkhtml2pdf 12.5 issues

So I created an additional JS file and now it looks like it's working.
Also tried ActionAsPDF but then I end up in authentication issues -> PDF shows login screen...

**Comment by webgio** [comment]
Great, thanks!

Il sab 23 mag 2020, 15:50 Joop Stringer <notifications@github.com> ha
scritto:
