### ISSUE TITLE
Exception when deployed to server

### ISSUE THREAD

**Issue by pauldambra** [webgio/Rotativa#23]
Apologies if I'm being slow - I've incorporated Rotativa and it works on my dev machine but when I try to use it on the server I receive the below:
## Server Error in '/' Application.

Unhandled Execution Error 
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Exception: 

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.  

Stack Trace: 

[Exception]
   Rotativa.WkhtmltopdfDriver.Convert(String wkhtmltopdfPath, String switches, String html) +822
   Rotativa.ViewAsPdf.CallTheDriver(ControllerContext context) +1027
   Rotativa.AsPdfResultBase.BuildPdf(ControllerContext context) +201
   Rotativa.AsPdfResultBase.ExecuteResult(ControllerContext context) +27
   Castle.Proxies.ControllerActionInvokerProxy.InvokeActionResult_callback(ControllerContext controllerContext, ActionResult actionResult) +21
   Castle.DynamicProxy.AbstractInvocation.Proceed() +69
   Glimpse.Mvc3.Interceptor.InvokeActionResultInterceptor.Intercept(IInvocation invocation) +431
   Castle.DynamicProxy.AbstractInvocation.Proceed() +204
   System.Web.Mvc.<>c__DisplayClass1c.<InvokeActionResultWithFilters>b__19() +33
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilter(IResultFilter filter, ResultExecutingContext preContext, Func`1 continuation) +613
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult) +263
   System.Web.Mvc.ControllerActionInvoker.InvokeAction(ControllerContext controllerContext, String actionName) +729
   System.Web.Mvc.Controller.ExecuteCore() +162
   System.Web.Mvc.ControllerBase.Execute(RequestContext requestContext) +159
   System.Web.Mvc.<>c__DisplayClassb.<BeginProcessRequest>b__5() +62
   System.Web.Mvc.Async.<>c__DisplayClass1.<MakeVoidDelegate>b__0() +15
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +1656
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +540

Server is Server 2008 R2 and application is dotNet 4.5

Call to Rotativa is

 return new ViewAsPdf("View", "~/Views/StaffExpenses/_ViewLayout.cshtml", claim)
                           {
                               PageSize = Size.A4,
                               PageOrientation = Orientation.Landscape,
                               PageMargins = {Left = 0, Right = 0, Top = 0, Bottom = 0}
                           };

Both Authenticated Users and the app pool have execute permissions on the files in the Rotativa folder which has deployed to the server with the application.

Project uses Windows Authentication

**Comment by ahmad1984** [comment]
Rotativa uses a temporary directory that names 'Rotativa' in root folder of the website or project. You must have this folder in your project or website.
It contains these files:
libeay32.dll
libgcc_s_dw2-1.dll
mingwm10.dll
README.txt
ssleay32.dll
wkhtmltopdf.exe

**Comment by chriscarreau** [comment]
Had a similar error, where it went fine on my local machine, but didn't work on the server. Turns out the only thing I had to do was to install the Visual C++ Redistributable Packages for Visual Studio 2013 on the server because rotativa needed it.

**Comment by bjarte** [comment]
@chriscarreau: Thanks, installing Visual C++ 2013 helped me as well. I had the same problem, things worked nicely locally, but not on the server (where Visual Studio is not installed).

**Comment by ahmad1984** [comment]
Have you added a folder named "Rotativa" in your website?

like this:
![untitled](https://cloud.githubusercontent.com/assets/10650049/6758773/0b7185ca-cf50-11e4-9a56-d32fcbf7a5a0.png)

**Comment by scottycroy** [comment]
FWIW, 

I had the same issue as described in this post. 
I installed the nuget package from within Visual Studio 2013. 
Hosting on Server 2008 R2. 

@ahmad1984  mentioned I needed the other files in the Rotativa folder in the root of the web. 
The files that @ahmad1984 mentioned was not included in the nuget package. 

I downloaded the git package and found the files in 

..\Rotativa-master\packages\Rotativa.1.0\content\Rotativa folder 

I uploaded the files, but it still did not work. 

I then downloaded wkhtmltopdf for x64 bit. 
Uploaded the files: 
wkhtmltoimage.exe
wkhtmltopdf.exe
wkhtmltox.dll 

Now this issue is resolved and everything works for me.

**Comment by bharrison1984** [comment]
I am having this same issue, but with wkHtmltoImage instead of PDF. It works fine locally, but just crashes with an exception on the server. I'm running in only Anonymous Auth mode on Sever 2012.
I have another project on this server that runs Rotativa, and it generates PDFs perfectly.

```
Stack trace:    at Rotativa.WkhtmlDriver.Convert(String wkhtmlPath, String switches, String html, String wkhtmlExe)
   at Rotativa.WkhtmltoimageDriver.ConvertHtml(String wkhtmltopdfPath, String switches, String html)
   at Rotativa.ViewAsImage.CallTheDriver(ControllerContext context)
   at Rotativa.AsResultBase.BuildFile(ControllerContext context)
   at LobbyKiosk.Controllers.HomeController.CreateIdCard(Int32 Visitor)
   at LobbyKiosk.Controllers.HomeController.Index(Nullable`1 Id)
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

**Comment by claudiomaia** [comment]
Para quem utiliza Asp.Net.MVC, volte a versão para 1.6.1 do rotativa que irá funcionar no servidor. Foi a solução que encontrei para resolver o problema (pelo menos por enquanto)
----------------------------------------------------------------------------------------------------------------

For those who use Asp.Net.MVC update in nuget to 1.6.1 of Rotativa that will work on the server. It was the solution I found to solve the problem (at least for now).

**Comment by bharrison1984** [comment]
I ended up downloading the newest wkhtmltoimage binary and replacing the one in the Rotativa directory. I did that once before but only on the server, so the next time I published my site it was overwritten with the old version that didn't work. I replaced my local version of wkhtmltoimage so subsequent publishes no longer break it on the server. All seems to be working great again.

**Comment by JustMaier** [comment]
What @scottycroy suggested worked for me as well.

**Comment by janessaallen** [comment]
@scottycroy where did you get these three files? 
wkhtmltoimage.exe
wkhtmltopdf.exe
wkhtmltox.dll
I'm having trouble locating them. Thanks in advance!

**Comment by scottycroy** [comment]
I downloaded them from information in the readme or by searching google. I
really don't remember which but i am certain it was one of them :)

**Comment by scottycroy** [comment]
I did download the 64 bit versions as the server i am using is 64 bit and
my dev machine is 64 bit too.

**Comment by JustMaier** [comment]
@janessaallen grab the installer [here](http://wkhtmltopdf.org/downloads.html). Once it's installed grab the files from /program files/wkhtmltopdf/bin/

**Comment by janessaallen** [comment]
Thanks. Still can't get it working. :-(

**Comment by 0lorak0** [comment]
I was having the same error as the OP with Rotativa 1.6.4 Nuget package.  I have another project that also has Rotativa, but with the 1.6.3-beta version that was not giving me errors on production.  I just replaced the 1.6.4 wkhtmltopdf.exe version with the 1.6.3-beta version and now I am not receiving the OP's error.

**Comment by janessaallen** [comment]
@0lorak0 where did you get the 1.6.3 version? I really need to get this working... :-(

**Comment by janessaallen** [comment]
I still cannot get this to work. This is the execution error:

[Exception]
   Rotativa.WkhtmltopdfDriver.Convert(String wkhtmltopdfPath, String switches, String html) +1364
   Rotativa.WkhtmltopdfDriver.Convert(String wkhtmltopdfPath, String switches) +63
   Rotativa.AsPdfResultBase.CallTheDriver(ControllerContext context) +123
   Rotativa.AsPdfResultBase.BuildPdf(ControllerContext context) +380
   Rotativa.AsPdfResultBase.ExecuteResult(ControllerContext context) +69
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +109
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +890
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult) +97
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +241
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +29
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +111
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +53
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +19
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +51
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +111
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +606
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +288

**Comment by bharrison1984** [comment]
I fixed it by swapping wkhtmltopdf.exe for the newest version. Make sure
you switch them within your project as well as on the server. That should
eliminate any problems that could appear next time you publish your
project. I was using the newest 1.6.4 nugget package.

-Sent from mobile

**Comment by 0lorak0** [comment]
@janessaallen  I uploaded it to google docs. The link is below.  It's just the wkhtmltopdf.exe version that came wtih 1.6.3-beta .
Notice though that bharrisson1984 swapped it for the newest version, which is the opposite of what I did and it worked for him.  Hopefully one of our solutions works for you.  Good luck!

https://drive.google.com/file/d/0BzI_u_O3vUM1aEppb3ZVZXNsc28/view

**Comment by janessaallen** [comment]
That's what I did wrong! It works now when I ONLY swap the .exe file. Thank you so much!!!

**Comment by 0lorak0** [comment]
@janessaallen That's great!  Did you swap with the 1.6.3-beta version like me or with the newer version like bharrison1984 ?

**Comment by janessaallen** [comment]
The 1.6.3-beta version like you. I hope this gets fixed for the future, though. Thanks for the help!

**Comment by bjarte** [comment]
I upgraded the Rotativa nuget package to 1.6.4. After that I started getting these errors on the server, but not locally:
System.Exception
   at Rotativa.WkhtmltopdfDriver.Convert(String wkhtmltopdfPath, String switches, String html)
   at Rotativa.WkhtmltopdfDriver.Convert(String wkhtmltopdfPath, String switches)
   at Rotativa.AsPdfResultBase.CallTheDriver(ControllerContext context)
   at Rotativa.AsPdfResultBase.BuildPdf(ControllerContext context)

I downloaded the newest version of wkhtmltopdf.exe and replaced the one in the project's Rotativa folder, and now the PDF generation works as expected.

**Comment by webgio** [comment]
Not sure I understood what's the error here... 1.6.4 has the latest wkhtmltopdf version, though it's the 32 bit version. Is this an issue related to running the 32bit version?

**Comment by Maxwellwr** [comment]
You must install Visual C++ 2013 Redistributable x86 on the server

**Comment by bjarte** [comment]
@webgio and @Maxwellwr Yes, you are both right. I already had the x64 redistributable installed, but not the x86. So what happened was NOT that I upgraded wkhtmltopdf.exe with a newer version, but that I replaced the x86 version with the x64 version.

Now I have installed the x86 redistributable as well on the server, and I can use the default wkhtmltopdf.exe that comes with the Rotativa nuget package.

**Comment by hubert17** [comment]
Hey guys! I followed @0lorak0 and it worked!
Just simply replace Rotativo/wkhtmltopdf.exe with this file below.
https://drive.google.com/file/d/0BzI_u_O3vUM1aEppb3ZVZXNsc28/view

**Comment by Banou** [comment]
Hello, i had the same problem on Windows server 2012 R2.
Following 0lorak0 solution resolved it !
Thanks !

**Comment by arracos** [comment]
Yep.  Had the same issue from the NuGet 1.6.4 package running on Windows Server 2008 R2 Datacenter.  Replaced the file back to the 1.6.3 beta supplied by @0lorak0 .  I'd suggest reverting the code back and updating the NuGet package until the next beta release comes out.  Thanks for the solution btw.

**Comment by josheluismusic** [comment]
Guys, i followed to @0lorak0. It's working

**Comment by darrenst** [comment]
Thank you. Changing the Exe worked for me.

However I suspect installing the "Visual C++ Redistributable Package for VS 2013." might have worked too as the exe was showing that "msvcp120.dll" was missing.

Thanks again.

**Comment by rostrander** [comment]
@0lorak0 thank you so much! I had the exact issue as that originally posted on this thread. When I attempted to run wkhtmltopdf.exe on Server 2012 R2 from cmd, but it also showed a missing "msvcp120.dll". I read that Server 2012 R2 does not automatically install the 32 bit version of that dll, and that some programs require it. Either way, the posted previous version of the exe solved the problem. Thanks so much to all of you!

**Comment by webgio** [comment]
Seems like it would be nice for Rotativa to guess OS support and install (or use at runtime) the relative wkhtmltopdf version. Currently uses 32bit for compatibility. I'll try to work on it. If anyone has time and ideas let me know, I'm willing to accept a PR.

**Comment by plamenyovchev** [comment]
Hi devs, 
I have a problem when the application is deployed to the server. 
I have the rotativa folder in the root folder of my project. But I am getting this exception:

Controller: Report, Action: CheckShiftReport, Exception:  \ System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Rotativa.WkhtmltopdfDriver.Convert(String wkhtmltopdfPath, String switches, String html)
   at Rotativa.WkhtmltopdfDriver.ConvertHtml(String wkhtmltopdfPath, String switches, String html)
   at Rotativa.ViewAsPdf.CallTheDriver(ControllerContext context)

I am using the latest version of Rotativa from NuGet. Could you please help.

**Comment by darrenst** [comment]
Does IIS_IURSRS have access to read/write?

**Comment by plamenyovchev** [comment]
Yes, this user has full permissions.

**Comment by UshaAiluri** [comment]
I followed the @0lorak0 but it is working locally but not on IIS

**Comment by aleksnadar5** [comment]
I am getting similar error

at Rotativa.WkhtmltopdfDriver.Convert(String wkhtmltopdfPath, String switches, String html) at Rotativa.WkhtmltopdfDriver.ConvertHtml(String wkhtmltopdfPath, String switches, String html) at Rotativa.ViewAsPdf.CallTheDriver(ControllerContext context) at Rotativa.AsPdfResultBase.BuildPdf(ControllerContext context) at Rotativa.AsPdfResultBase.ExecuteResult(ControllerContext context) at System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult) at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult) at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)

And the link above solved my problem. 
https://drive.google.com/file/d/0BzI_u_O3vUM1aEppb3ZVZXNsc28/view

Thank you for posting!

**Comment by joshyates1980** [comment]
@0lorak0 Is there anywhere else I can download 1.6.3-beta / wkhtmltopdf .exe.   google drive is blocked within the network I'm on.

**Comment by 0lorak0** [comment]
@joshyates1980
I created a repo with it: https://github.com/0lorak0/wkhtmltopdf_Rotativa
Also, on dropbox: https://www.dropbox.com/s/szbl39cszpubjuj/wkhtmltopdf.exe?dl=0

**Comment by joshyates1980** [comment]
Thanks @0lorak0.  I downloaded the wkhtmltopdf file and replaced the newer one on my server with the one you provided.  It solved my issue and I now can download pdf.

**Comment by rossifederico** [comment]
I fixed installing Visual C++ 2013 Redistributable x86. Thanks @Maxwellwr

**Comment by Tipigao** [comment]
Eu corrigi esse bug, fiz o download pelo nuget do pacote Rotativa PDF no Visual Studio normalmente, na minha máquina era a versão 64 bits. Quando fui publicar no servidor, baixei no site oficial http://wkhtmltopdf.org a versão 32 bits do aplicativo wkhtmltopdf, depois peguei apenas a versão 32 bits do executável e substitui na pasta Rotativa. Funcionou que é uma beleza!
 1) Download Rotativa PDF pelo Nuget do Visual Studio normalmente
 2) Compilar e publicar no servidor
 3) Download wkhtmltopdf 32 bits em http://wkhtmltopdf.org
 4) Substituir Rotativa/wkhtmltopdf.exe pela versão 32 bits

**Comment by fabiohiga** [comment]
I fixed installing wkhtmltopdf from http://wkhtmltopdf.org/downloads.html on server

**Comment by smezae** [comment]
I fixed it copying an older version of wkhtmltopdf.exe from an mvc app that works fine with rotativa into the new project with the problem...and magically the issue is gone. I'm using windows server 2012 to host the app

**Comment by paulocampez** [comment]
Worked for me.
Thank You
------------------------------------------------------
claudiomaia commented on 4 Apr 2015
Para quem utiliza Asp.Net.MVC, volte a versão para 1.6.1 do rotativa que irá funcionar no servidor. Foi a solução que encontrei para resolver o problema (pelo menos por enquanto)

For those who use Asp.Net.MVC update in nuget to 1.6.1 of Rotativa that will work on the server. It was the solution I found to solve the problem (at least for now).

**Comment by zaiken** [comment]
@chriscarreau: Thanks, installing Visual C++ 2013 helped me too.

**Comment by velikocakk** [comment]
I am getting same error message. I have downloaded newest version from the website which is http://wkhtmltopdf.org/downloads.html. I am using Godaddy. I can not install anything to Godaddy's servers.

**Comment by UshaAiluri** [comment]
We can use customized class library which is available in onlie. We can
download and use those libraries instead of rotativa.

**Comment by velikocakk** [comment]
can you give me the link please ?

**Comment by UshaAiluri** [comment]
https://daveaglick.com/posts/using-aspnet-mvc-and-razor-to-generate-pdf-files

https://www.danylkoweb.com/Blog/creating-dynamic-pdfs-in-aspnet-mvc-using-itextsharp-EV

**Comment by joaocarlosleme** [comment]
Downgrading from 1.6.4 to 1.6.1 fix the error to me as well. Wonder why this issue has been closed if the problem still persist. @webgio ?
