### ISSUE TITLE
Rotativa on HTTPS not loading the css 

### ISSUE THREAD

**Issue by BGMOmar** [webgio/Rotativa#234]
Hello so i was generating view as pdf in my website with http link and it was working when i moved into https the pdf is loading but it its not loading the css , i have the css link in the head as :
`<link rel="stylesheet" href="/css/style.css">`
Tried using other styles like using the ~ or Url.Content or even using the https://mydomain/css/... but didn't want to work any ideas ?

**Comment by MarteFilho** [comment]
I have the same problem here, it works locally and in docker container.
In azure with the same image and configuration doesnt work.
I have tried @Url.Content, "~", @Url.Content(System.IO.Path.Combine(Environment.WebRootPath, "RotativaAssets", "css", "style.css")) but none works.

**Comment by BGMOmar** [comment]
@MarteFilho I actually found a work around to make it work , the problem for me was on the server had to add the domain and its ip adress in the hosts.txt file on the windows server.
