### ISSUE TITLE
Rotativa and WebAPI

### ISSUE THREAD

**Issue by yyie** [webgio/Rotativa#38]
Hi, I want to use BuildPdf method inside a WebAPI action. I want to use BuildPdf to send some PDF mails. The BuildPdf method requires the Mvc.Context and not the ApiControllerContext. Somebody know if is it possible to used in WebApi?

**Comment by JustMaier** [comment]
Submitted [Pull Request](https://github.com/webgio/Rotativa/pull/88) to address this.

**Comment by pjdupreez** [comment]
Had any luck with this? I am also looking for this functionality.

**Comment by JustMaier** [comment]
@pjdupreez you can grab my fork/pull request for a version that works without the HTTPContext.

**Comment by pjdupreez** [comment]
Thanks, I will definitely have a look

**Comment by 2E0PGS** [comment]
I suggest we re open this issue. Merge the pull request and then close it.
