### ISSUE TITLE
No CSS formatting in generated PDF (works on localhost)

### ISSUE THREAD

**Issue by darrel-oneil** [webgio/Rotativa#39]
We have Rotativa working fine when running on localhost but when we deploy to our development server the PDF is successfully created from the view but all colour and formatting is lost?

We have checked and everything appears to have been deployed successfully.

**Comment by Excolo** [comment]
I have the same issue but I can't use ActionAsPdf instead of ViewAsPdf, as this causes the 'Qt: Untested Windows version 6.2 detected!' error.

**Comment by Spencerooni** [comment]
@webgio Would you have any other suggestions or things to check as to why css and images would not appear when using ViewAsPdf? Works on my machine, however not the case for others on my team.

**Comment by wmkDev** [comment]
@Spencerooni, had this problem today on new production server (windows server 2012), the pdf open without css and images but the solution was easy:

Modify hosts file (c:\Windows\System32\Drivers\etc\hosts)
found the lines:

# localhost name resolution is handled within DNS itself.
#	127.0.0.1       localhost
#	::1             localhost

and uncomment (remove "#") from 127.0.0.1 and ::1. 

Hope it helps.

**Comment by VinS101** [comment]
We have the same issue. No solution has worked for us so far  😢

**Comment by HeyJhon** [comment]
I think that is a problem with http/https because i have an app in iis7 and when a user is conected in the same network that the server, the PDF is generated correctly with CSS and Images.

When user conected from another network to reach the server,  PDF is generated without Images and CSS.
