### ISSUE TITLE
Images Not Showing

### ISSUE THREAD

**Issue by mxmissile** [webgio/Rotativa#41]
I'm having trouble getting a simple image to show up in the generated pdf, here is my view and I am using ViewAsPdf()

Are there any gotchas or requirements when including an image in the view/pdf?

```
<h2>test</h2>

<div id="proof-image">
    <img src="/action-that-generates-an-image" />
</div>
```

**Comment by CaptainDashenka** [comment]
Same here! long live "AllowAnonymus"!

**Comment by bharatiborde** [comment]
If you are using <img> tag and adding height and width to it then make sure that you should add it in style tag 
e.g., <img src="imagepath" style="width:100px; height:100px">

**Comment by bhushanmorwal** [comment]
@bharatiborde  Thank you! you save the world :)
