### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by KirbyFox** [webgio/Rotativa#47]
I have developed a site using Rotativa and it works perfectly on my development machine.

However, when I upload it to the live version of the site on shared hosting, the PDF generation returns the error '504 Gateway Timeout'.

From what I can tell, the problem seems to occur within WkhtmltopdfDriver.cs and the following function.

private static byte[] Convert(string wkhtmltopdfPath, string switches, string html)

I think I've narrowed it down to the point at which the code reads the output generated from the process that calls wkhtmltopdf.exe.

while ((read = sOut.Read(buffer, 0, buffer.Length)) > 0)

If anyone has any suggestions, I'd be most grateful.

**Comment by bunomonteiro** [comment]
For those who are still having the same problem:

1- Update "wkhtmltopdf" to the newest version: 
> https://wkhtmltopdf.org/downloads.html

2- Configure IIS: Increase the connection time-out:
![image](https://github.com/webgio/Rotativa/assets/5221494/692fafbe-7b5e-4635-8e7c-4088de932a51)

3- Ensure that the time-out is also configured in the proxies (NGINX, HAProxy, etc.)
