### ISSUE TITLE
Version not reliant on .exe file

### ISSUE THREAD

**Issue by NikolajDL** [webgio/Rotativa#48]
Is there hope for a version that doesn't require execution of a .exe file, e.g. a version of Rotative that uses the .dll file instead? 

The host chosen by my client doesn't allow execution of .exe files.

**Comment by h-morales** [comment]
Why not have a version that uses exe and a version that uses dll?
Anyway, this is a nice tool!

**Comment by Excolo** [comment]
https://github.com/gmanny/Pechkin does almost the same thing, using the dll instead of the exe. 

I personally stopped using it (both Pechkin and Rotativa), not out of want, but because it's reliant on GDI+ being available on the host, and my new host, Azure Web App, doesn't support GDI+. :-(
