### ISSUE TITLE
Problem with Azure

### ISSUE THREAD

**Issue by fvoska** [webgio/Rotativa#49]
It works fine on my development server when I run from Visual Studio 2012, generates PDF from a View. However, when I publish to Azure and try to return PDF, it just says "Waiting for oppradovi.azurewebsites.net...". Everything else works just fine on Azure, maybe it's an issue with code execution permissions once it's on Internet server and not on local dev server.

Maybe it's worth mentioning that I'm on a free trial Azure account which could have caps on CPU utilization. It's not crucial part of my application, but it would be nice to get it working :)

**Comment by martinkearn** [comment]
Are there any plans to make this work with the Azure Web App or are you completely blocked by the fact that Azure Web App prevents executables?
