### ISSUE TITLE
ActionAsPdf renders login view

### ISSUE THREAD

**Issue by david-ju** [webgio/Rotativa#50]
When I use ActionAsPdf in an MVC app with forms authentication enabled, I get the login screen rendered in my pdf.
new ActionAsPdf("Print"); // Renders login view
new ViewAsPdf("Print", model); // Renders correctly

**Comment by Balirezaei** [comment]
Hi 
Can you explain more about 'change permissions to the virtual directory in the top level application web.config' ? I can't understand , I searched on Google more than 3 weeks but I couldn't find any thing about this.
my project is asp mvc5 and I use Microsoft.Asp Net.Identity for authentication .
I couldn't fix this problem but I add   [AllowAnonymous] attribute to my ActionResult and pdf report works but I should read an image from web service  in the view and pdf didn't show image.
" src='@Model.MAPP_Member.WorkerTraitCodeScores[j].TraitCategoryChartURL' "

thanks a lot

**Comment by janessaallen** [comment]
I'm having a similar issue. Any resolution?
