### ISSUE TITLE
IIS 8 compatability?

### ISSUE THREAD

**Issue by Munk74** [webgio/Rotativa#53]
Is Rotativa 1.6.1 tested on IIS 8?, i am facing some problems with images and css in ViewAsPdf, and exception with ActionAsPdf

Localized the exeption in ActionAsPdf coming from wkhtmltopdf.exe with ReturnCode 1   
Qt: Could not initialize OLE (error 80070005)....  access denied.

I can execute the wkhtmtopdf.exe with pdf output from console as the IIS user with no problems.

**Comment by bjarte** [comment]
Hi 

I tried Rotativa 1.6.3-beta in Visual Studio 2013's IIS Express and get the same errors Munk74 was struggling with.

Using ViewAsPdf, I don't get any images or styling. Using ActionAsPdf I always get a blank pdf.

**Comment by bjarte** [comment]
I have the issue with styling missing on VS 2013's IIS Express, IIS 6.1 running on Windows 7 and IIS 7 running on Windows Server 2008 R2. So the problem apparently has nothing to do with which version of IIS you are running.

**Comment by webgio** [comment]
You should check the images and css paths. With latest Rotativa version some problems with path resolution should be gone. You could try by simply installing the beta nuget package (Install-Package Rotativa -Pre)

**Comment by bjarte** [comment]
I ended up using UrlAsPdf(), which seems to be the most stable option. The only issue I came across here, is that I cannot use partial urls, like "/mypage/content" in a load balanced environment.

This probably isn't Rotativa's fault, but I had to use the full url to the load balancer, like "http://mysite/mypage/content" to get it to work.

**Comment by webgio** [comment]
As I wrote before, some issues could come from path to external resources (images and css) that are not correctly resolved (mapped) fro Rotativa. Pre release version should address those issues.

**Comment by bjarte** [comment]
Thanks for putting in the work, it's really appreciated!
