### ISSUE TITLE
Special characters in text rendering as codes

### ISSUE THREAD

**Issue by saisworld** [webgio/Rotativa#58]
Hi ,

I have a some special character in text like '£' or bullet points. These are values entered by users in a textarea field. I'm displaying that text in a label. Its displaying fine in the view but when exporting that to pdf its converting the special characters to some codes in the pdf. 

Not sure if this is related to wkhtmltopdf or something related to encoding which am missing. Any suggestions please?

eg- 

text  displayed in view:
1st supervisor x 1 @ £1000 Provisional 2nd supervisor x 2 @ £500 each 2nd Supervisor DBA x 1 @ £500

Text rendered inside pdf: (without spaces inbetween the codes)
1st supervisor x 1 @ & # 163 ;1000 Provisional 2nd supervisor x 2 @ & # 163 ;500 each 2nd Supervisor DBA x 1 @ & # 163 ;500

Thanks,
Sai

**Comment by webgio** [comment]
Can't reproduce. Perhaps was due to server env.
