### ISSUE TITLE
Table-break on 2 pages incorrectly

### ISSUE THREAD

**Issue by Ba-SS-eM** [webgio/Rotativa#59]
when i tried to convert a table with many rows that don't fit in one page, table breaks incorrectly because part of row is displayed in one page and remain part is displayed in the other page 
![temp](https://cloud.githubusercontent.com/assets/7665312/3050623/32ac6ea0-e17d-11e3-8510-36575cec1874.png)

is there any options can i configure to handle this issue dynamically?

**Comment by ganeshjr** [comment]
Hi, I am using version 1.6.4 and I have the same issue. My table rows are split even with the page break css. Did you upgrade to a higher version of Rotativa and notice the page break issue again? 
Thanks,
Ganesh

**Comment by parissge** [comment]
I agree, version 1.6.4 and even with CSS the page break is not applied correctly.
I tried my page with the print feature of the browser and page breaks are correct, when generating pdf with the library they are wrong.

**Comment by ivanovevgeny** [comment]
Maybe Rotativa should be updated to  wkhtmltopdf 0.12.2.4
https://github.com/wkhtmltopdf/wkhtmltopdf/commit/5dea2532977e5e9fbcb8da7aa3bd399b257096f4

**Comment by webgio** [comment]
Please check if new pre-release version solves problem .
`Install-Package Rotativa -Pre`
