### ISSUE TITLE
doesn't work for authorized actions in ASP.Net MVC 5.1

### ISSUE THREAD

**Issue by raminmjj** [webgio/Rotativa#60]
PDF generated is my login page.

**Comment by Balirezaei** [comment]
My project is asp mvc5 and I use Microsoft.Asp Net.Identity for authentication .
I couldn't fix this problem but I add [AllowAnonymous] attribute to my ActionResult and pdf report works but I should read an image from web service in the view and pdf didn't show image.
" src='@Model.MAPP_Member.WorkerTraitCodeScores[j].TraitCategoryChartURL' "

**Comment by norris1976** [comment]
I have the same issue. This is NOT solved.
@webgio - any indication as to when this might be fixed?

Thanks dude!

**Comment by Balirezaei** [comment]
My problem is solved. I saved the url to my local and added original path  like this https://www.google.com/images/srpr/logo11w.png and that worked :).
This Component Has problem with gif image too .If you have gif images you should save that to png or jpg.

**Comment by webgio** [comment]
When you get to login page for authorized actions then the problem is about authentication cookies. You should check what cookie is your app using and pass it to Rotativa in the FormsAuthenticationCookieName property.
