### ISSUE TITLE
issue with pdfResult.BuildPdf(this.ControllerContext)

### ISSUE THREAD

**Issue by venom1978** [webgio/Rotativa#61]
hi,

I need to generate a pdf and save it on the server without sending it back to the user.
I saw that I could use the BuildPdf to do this, but when I do it gives me the following error
Qt: Untested Windows version 6.2 detected!
Error: Failed loading page http://localhost:50835/Reports/Reports/GetAdminDefectsOutstandingReportData1?AuditZone=1&AuditZoneText=Powercor - Zone 4&AuditMonth=May 2014&PrintReport=False (sometimes it will work just to ignore this error with --load-error-handling ignore)

The code is

  public ActionResult GetAdminDefectsOutstandingReportData(ReportViewModel viewModel)
       {
           var pdfResult = new ActionAsPdf("GetAdminDefectsOutstandingReportData1", viewModel) { FileName = "Test.pdf" };

```
       var binary = pdfResult.BuildPdf(this.ControllerContext);

       return File(binary, "application/pdf");
   }
```

I am using version 1.6.1

-- just realised in the GetAdminDefectsOutstandingReportData1 action method I was calling ActionPDF - my bad .. all good

**Comment by rinkeshcubes** [comment]
@venom1978  Hello i am getting same error when  i am using customeswtiches option in  code my code as below 
string CustomSwitch = "--print-media-type --header-center \"PS\"   Page: [page]/[toPage]\"" +
                    " --footer-line --footer-font-size \"9\" --footer-spacing 6 --footer-font-name \"calibri light\"";
                var rotativaOptions = new DriverOptions() { CustomSwitches = CustomSwitch };
 var action = new ActionAsPdf("DownloadPDInfo", new { patientId = patientId })
                {
                    FileName = fileName,
                    RotativaOptions = rotativaOptions
                };
                var pdfBytes = action.BuildPdf(this.ControllerContext);  <-- error when converting 
can you please help me how you fix your error
