### ISSUE TITLE
Qt: Untested Windows version 6.2 detected!

### ISSUE THREAD

**Issue by AvinashTompe** [webgio/Rotativa#64]
its working on my local system but after hosting on server getting following error
i am using windows server-2012  and iis 8.0

Qt: Could not initialize OLE (error 80070005)
Error: Failed loading page http://xxxxxxx.com/CompanyUsers/Invoices/viewPdf/393 (sometimes it will work just to ignore this error with --load-error-handling ignore)
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.Exception: Qt: Untested Windows version 6.2 detected!
Qt: Could not initialize OLE (error 80070005)
Error: Failed loading page http://xxxxxxxxxx.com/CompanyUsers/Invoices/viewPdf/393 (sometimes it will work just to ignore this error with --load-error-handling ignore)

Source Error:

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace:

[Exception: Qt: Untested Windows version 6.2 detected!
Qt: Could not initialize OLE (error 80070005)
Error: Failed loading page http://xxxxxxxxxxx.com/CompanyUsers/Invoices/viewPdf/393 (sometimes it will work just to ignore this error with --load-error-handling ignore)
]
   Rotativa.WkhtmltopdfDriver.Convert(String wkhtmltopdfPath, String switches, String html) +822
   Rotativa.AsPdfResultBase.CallTheDriver(ControllerContext context) +31
   Rotativa.AsPdfResultBase.BuildPdf(ControllerContext context) +186
   Rotativa.AsPdfResultBase.ExecuteResult(ControllerContext context) +27
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +109
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +890
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult) +97
   System.Web.Mvc.Async.<>c__DisplayClass1e.<BeginInvokeAction>b__1b(IAsyncResult asyncResult) +231
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +29
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +111
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +53
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +19
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__4(IAsyncResult asyncResult, ProcessRequestState innerState) +51
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +111
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +606
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +288

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.17929

**Comment by ThatsIT** [comment]
Any news on this I have the same problem also

**Comment by another-superman** [comment]
It seems the problem was with wkhtmltopdf. I ended up plugging in a newer version of the executable (wkhtmltopdf.exe) and that fixed my problem. The version I'm using is v0.12.1, which still seems to be the most recent version. You can download that here:

[http://wkhtmltopdf.org/downloads.html](http://wkhtmltopdf.org/downloads.html)

**Comment by ThatsIT** [comment]
Thanks I was using the nugget package, I had 1.6.1,I updated to 1.6.3-beta than solved my problem
http://www.nuget.org/packages/Rotativa/

**Comment by lkeel75** [comment]
I was getting the 'Untested version' error randomly on my hosted site (hosted by Arvixe).  I have been working with them for some time trying to figure out why the functionality randomly works using version 1.6.1.  I have a function that prints the same data for a list of students.  Sometimes it works and other times calling the same section of code won't work.  I upgraded to 1.6.3 and get a new error every time now.  The new error has no message, but does have the same call stack as the 'Untested version' error from 1.6.1.  The 1.6.3 version works fine if only have 1 student but errors every time if have multiple students.  This is the same view & function that randomly works with 1.6.1.  Any help suggesting how to resolve or debug this would be greatly appreciated.

**Comment by webgio** [comment]
@lkeel75 what is the server running on? OS version and IIS version. 32or 64 bit?

**Comment by lkeel75** [comment]
This is being hosted by Arvixe so I am going on what they have told me.  From what I have gathered: Windows Server 2012 64 bit (confirmed by support team), IIS: Not sure.

**Comment by lkeel75** [comment]
I have tried to use the package 1.6.1 and just copied the wkhtmltopdf.exe from the lastest install to the packages folder.  But this did not work either.

**Comment by webgio** [comment]
@lkeel75 you wrote you get no errors? What do you mean? No exception? Also, is this happing on a specific view and other views work?

**Comment by webgio** [comment]
have you tried 1.6.4-beta?

**Comment by lkeel75** [comment]
By no errors I mean that it works.  The view that I am creating is being returned as a PDF.  I click the same button again to repeat the exact same workflow and I get the error.  I have 4 different views that I use the print to pdf functionality on.  I get this error randomly on all 4 as well as it randomly works on all 4 views.  There is no rhyme or reason as to why it works sometimes and not others.  Especially in the cases where 1.6.1 was returning 'untested os version'.

**Comment by lkeel75** [comment]
I have not tried 1.6.4-beta

**Comment by webgio** [comment]
If you feel to, you can manually replace wkhtmltopdf to the Windows (MinGW-w64) version here: http://wkhtmltopdf.org/downloads.html
I don't really know the internals of wkhtmltopdf though, it's just another try you can take. Seems a problem with the server specific setup.

**Comment by lkeel75** [comment]
I agree on the server setup, but Arvixe is trying to push it to the software (as one would expect).  Is the 1.6.4-beta stable?  If so, then I will try it.  I will also try your other suggestion.  THANKS!

**Comment by webgio** [comment]
I’ll turn it to release soon, I think you can use it, didn’t get any negative feedback.

**Comment by serefbilge** [comment]
Hi, I have the same problem. My site is in Arvixe hosting (Windows Server 2012 64 bit) and gave the error below*. Some times it doesn't give error but it takes long to get result. 

And also, I tested the same web project in another server(not a shared one) which of 64 bit Windows Server 2008 R2 Enterprise and IIS 7.5 system and it works fine on this server without error.

* The Error as below:

[Exception]
Rotativa.WkhtmlDriver.Convert(String wkhtmlPath, String switches, String html, String wkhtmlExe) +973
Rotativa.WkhtmltopdfDriver.Convert(String wkhtmltopdfPath, String switches) +56
Rotativa.AsPdfResultBase.WkhtmlConvert(String switches) +62
Rotativa.AsResultBase.CallTheDriver(ControllerContext context) +83
Rotativa.AsResultBase.BuildFile(ControllerContext context) +250
Rotativa.AsResultBase.ExecuteResult(ControllerContext context) +66
System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult) +13
System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +56
System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +420
System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult) +52
System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +173
System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +100
System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +27
System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +13
System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +36
System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +54
System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +41
System.Web.Mvc.Controller.<BeginExecute>b__15(IAsyncResult asyncResult, Controller controller) +12
System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +28
System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +54
System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +31
System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +10
System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +21
System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +36
System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +54
System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +31
System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9651188
System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155

**Comment by lkeel75** [comment]
I hope you get it resolved.  I worked with the support team at Arvixe but I finally gave up because they kept saying it was a software problem.  Hard to blame the software in my opinion if it works sometimes and not others.

**Comment by serefbilge** [comment]
@lkeel75 After that what is your solution of conversion to pdf ?

**Comment by lkeel75** [comment]
@serefbilge Unfortunately I have stuck with this solution for now.  I am in the process of moving my site away from Arvixe and hoping that moving it into Azure will resolve this issue.

**Comment by serefbilge** [comment]
@lkeel75 I'm considering to move my site also. I'm waiting for support of arvixe.

**Comment by serefbilge** [comment]
@lkeel75 I get  an advice from arvixe support to either upgrade to a BusinessClass account or reduce my resource consumption on my current site. They say that I was hitting my memory limit as well as my CPU limit.

Do you have Personal account or BusinessClass account ?

**Comment by lkeel75** [comment]
@serefbilge I have the Personal account.  However I do have a hard time believing this is an issue with memory for me.  I currently only have about 100 users and there is no way any of them were using during my testing times.

**Comment by serefbilge** [comment]
At the end, I made them believe it is not a memory issue. I uploaded my
project to another shared hosting(turhost) using my mate's account. It
worked perfect(about 1.5 sn) and I showed to support member. Then, I quit
from arvixe. The support member asked me if I want to refund; I accepted.

You can try on another shared hosting; I believe it will work perfect.

2015-04-15 21:59 GMT+03:00 lkeel75 <notifications@github.com>:

> @serefbilge <https://github.com/serefbilge> I have the Personal account.
> However I do have a hard time believing this is an issue with memory for
> me. I currently only have about 100 users and there is no way any of them
> were using during my testing times.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webgio/Rotativa/issues/64#issuecomment-93532555>.
>



-- 
Şerafettin BİLGE
Dünya Bankası Bilişim Danışmanı
E-posta : serafettin.bilge@saglik.gov.tr

**Comment by lkeel75** [comment]
Well I ended up using my BizSpark license and moving everything to Microsoft Azure Cloud Service.  I originally started as an Azure website, but things still would not work.  But everything works just fine as a cloud service.

**Comment by alexcrivelente** [comment]
I could fix this problem by adding an entry at the "hosts" file in c:\windows\system32\drivers\etc
The entry must resolve the server name to it's local IP address.

**Comment by ccsaxton** [comment]
I had a similar problem with wkhtmltopdf and the problem was within the HTML that was created. I had written some XSL to generate HTML and in the test environment the generated links embedded in the HTML were correct but if any links that are generated in the HTML document (ie CSS links) cannot be resolved then it threw out this spurious error. When I corrected the CSS links in the document so that they resolved correctly then all worked fine. Hope this helps someone in the future who has this same issue
