### ISSUE TITLE
Rotativa had problems with css style on server

### ISSUE THREAD

**Issue by Supermakaka** [webgio/Rotativa#69]
Hi

I am using rotativa in my ASP.net MVC project. I am using ViewAsPDF as return type. The problem is that on local enviroment everything runs smoothly, the css style is getting applied to PDF correctly, but when I deploy my app on prod server and I try to get PDF file, server returns it only after ~ 5 minutes without CSS style applied. If I gave style straight to the atribute style="..." it works. Where can I find the problem, and how to solve it? If I change method ViewAsPdf to ActionAsPDF I am getting error:

Server Error in '/' Application.

Error: Failed loading page http://myapp.com/FinishingSchedules/PrintScheduleDetails/2?Name=Schedule No.2&CostPerSquareFootMaterial=0.06&CostPerSquareFootLabor=54&DirectCostOfMaterialsAndLabor=108.12&TotalPriceWithMarkUp=118.93&TotalJobSize=2&ProductionTime=36&MaterialsQuantities=System.Collections.Generic.List`1[WebSite.ViewModels.FinishingSchedules.MaterialsQuantities](sometimes it will work just to ignore this error with --load-error-handling ignore)

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Exception: Error: Failed loading page http://myapp.com/FinishingSchedules/PrintScheduleDetails/2?Name=Schedule No.2&CostPerSquareFootMaterial=0.06&CostPerSquareFootLabor=54&DirectCostOfMaterialsAndLabor=108.12&TotalPriceWithMarkUp=118.93&TotalJobSize=2&ProductionTime=36&MaterialsQuantities=System.Collections.Generic.List`1[WebSite.ViewModels.FinishingSchedules.MaterialsQuantities](sometimes it will work just to ignore this error with --load-error-handling ignore)

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[Exception: Error: Failed loading page http://myapp.com/FinishingSchedules/PrintScheduleDetails/2?Name=Schedule No.2&CostPerSquareFootMaterial=0.06&CostPerSquareFootLabor=54&DirectCostOfMaterialsAndLabor=108.12&TotalPriceWithMarkUp=118.93&TotalJobSize=2&ProductionTime=36&MaterialsQuantities=System.Collections.Generic.List`1[WebSite.ViewModels.FinishingSchedules.MaterialsQuantities] (sometimes it will work just to ignore this error with --load-error-handling ignore)
]
   Rotativa.WkhtmltopdfDriver.Convert(String wkhtmltopdfPath, String switches, String html) +570
   Rotativa.AsPdfResultBase.CallTheDriver(ControllerContext context) +26
   Rotativa.AsPdfResultBase.BuildPdf(ControllerContext context) +128
   Rotativa.AsPdfResultBase.ExecuteResult(ControllerContext context) +19
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult) +13
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +56
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +420
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult) +52
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +173
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +100
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +27
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +13
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +36
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +54
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +39
   System.Web.Mvc.Controller.<BeginExecute>b__15(IAsyncResult asyncResult, Controller controller) +12
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +28
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +54
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +29
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +10
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +21
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +36
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +54
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +31
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9633216
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.

Thanks for any help!

**Comment by chrisdemetriad** [comment]
Any news on this?

**Comment by chriscarreau** [comment]
Had a similar error, where it went fine on my local machine, but didn't work on the server. Turns out the only thing I had to do was to install the Visual C++ Redistributable Packages for Visual Studio 2013 because rotativa needed it.

**Comment by itanex** [comment]
If your site runs under any HTTPS and the request for your PDF is behind an [Authorize] action the CSS can cause issues. I created a simple method to address this by embedding the CSS into the PDF render instead; and solved the problem. 

Also occurs for ANY other external resources falling under the same conditions.

**Comment by martic** [comment]
Add a User with privileges to the server to run 
then

**Comment by itanex** [comment]
+martic what kind of user? A user on the machine that runs IIS? Or a user in the authentication structure of the website? Because all authorization on my site is done through AD as pass through so I done have passwords; only usernames.

**Comment by martic** [comment]
Create an additional AD user just for this purpose, so you do know the password.
I may be wrong but the authorization with in the MVC pages seam to abide by the pass through auth, But the CSS, Images and other resources are not accessible using the pass through because they are additional requests, so the additional user credentials are used just for the resources loaded through HTTP / HTTPS.

**Comment by webgio** [comment]
Issue from two years ago, bit it seems to me different topics in here, probably related more to wkhtmltopdf itself.

**Comment by gondaliyabhautik** [comment]
> I created a simple method to address this by embedding the CSS into the PDF render instead; and solved the problem.

**How do you write code to embed CSS into PDF rendering ?**
See my code below to generate PDF, it works well except it's missing images and CSS formatting

**View:**
<div style="float:right;">
        <a href="@Url.Action("PrintPartialViewToPdf", new { id = ViewBag.ID, viewName = "_CheckListStepProcessor.cshtml" })" class="space btn btn-default btn-primary">Save as PDF</a>
    </div>

**Controller Action:**
public ActionResult PrintPartialViewToPdf(int id, string viewName)
{
      DOCUMENT doc = db.DOCUMENTS.Find(Convert.ToInt64(id));           
      var report = new Rotativa.PartialViewAsPdf("~/Views/Home/" + viewName, doc);
      return report;
}
