### ISSUE TITLE
Problem with online image

### ISSUE THREAD

**Issue by gwenael-louandre** [webgio/Rotativa#71]
Hello,

I tried to use the ViewAsPDF to export one of my details view. I have the CSS, the text and image resources but I don't succeed in having online images. I tried with an image sent by a controller (with a return File) and with an online image available on yahoo. Each I have a litlle square instead of my image.

Before I used ActionAsPDF and it worked but I have a security problem and according to the #57 issue I tried to use ViewAsPDF. Could you tell me if there is a restriction with online image?

Thanks.

**Comment by lkeel75** [comment]
I am also seeing this problem.  Any updates would be appreciated!

**Comment by mossybreen** [comment]
For me this works in a local dev environment, but the images are not being rendered when my web app is published. I'm not sure why it is treated any different.

**Comment by TOMKT** [comment]
I'm facing the exact same problem, it looks like the pdf gets rendered before the images are loaded

**Comment by webgio** [comment]
Can I look at the image? and the HTML fragment that loads it. I would like to reproduce the problem.
