### ISSUE TITLE
background-repeat Is not Working on 1.6.1 

### ISSUE THREAD

**Issue by BabakGoshtasbi** [webgio/Rotativa#73]
Using ASP.Net MVC 5 and installed  Rotativa 1.6.1 and the images are loading fine except for this one scenario where we have an image as a background with attribute "background-repeat:repeat-y;". Do you have any solution for this?
I tried different approaches and I am sure it is not a permission issue or path issue . For example: I encoded the image to base 64 or I converted the entire Razor view result into string and show it as raw HTML "@Html.Raw()" but didn't solve the issue.

**Comment by webgio** [comment]
@BabakGoshtasbi Did you solve this? Have you tried the latest Rotativa version?

**Comment by BabakGoshtasbi** [comment]
Sorry for late response , yes it is resolved.
