### ISSUE TITLE
Should allow us to change Content-Disposition

### ISSUE THREAD

**Issue by akonyer** [webgio/Rotativa#75]
Instead of forcing to download as an attachement, I think we should be allowed to choose "inline" so that we can attempt to display the pdf in the browser.

**Comment by webgio** [comment]
@akonyer what browser are you using? OS? I see the Pdf in the browser already.

**Comment by akonyer** [comment]
I am using Chrome on Windows 8.1

I was getting a download/save dialog without content-disposition being set to inline.

**Comment by webgio** [comment]
I can't reproduce your setup now, I'm on MacOS and Win7 VM. Can you make a fork and try to fix it yourself? I'll be glad to accept a Pull request. :)

**Comment by webgio** [comment]
@akonyer  Oops, sorry, seems you already submitted the pull request. But it doesn't allow do auto merge. I can do the changes by hand, if you want. Otherwise you should submit again.

**Comment by akonyer** [comment]
I'll take a look and submit a new pull request.

Thanks
