### ISSUE TITLE
Why does the Rotativia Nuget modify the MVC reference in Web.Config

### ISSUE THREAD

**Issue by itanex** [webgio/Rotativa#78]
After installing the NuGet package into a few projects I noticed that it updated the binding redirect for MVC from 1.0.0.0 to 0.0.0.0. Why is this?

**Comment by webgio** [comment]
@itanex that's because Rotativa references Asp.net mvc 3 and you project references a more recent version. Are you experiencing problems with it?

**Comment by itanex** [comment]
It doesn't cause a functional problem, it just causes code reviewers where I work to ask why that change was made. I just wanted to make sure it was something that wasn't specific to your library, which would just be weird if it was.
