### ISSUE TITLE
ViewAsPdf does not execute on page javascript as ActionAsPdf does

### ISSUE THREAD

**Issue by akonyer** [webgio/Rotativa#79]
I am unable to execute javascripte on the page load with ViewAsPdf.

Even if this is one only thing on the page (with js libraries obviously)

<script type="text/javascript">

   $(document).ready(function()
   {
      $.getJSON('/Controller/MethodName', { "id": 98885 }, function (data) {
          //do stuff
      });
   });   
</script>

The controller is not called. The javascript doesn't seem to be called at all, regardless of what I pass to Rotativa.

**Comment by llCorvinSll** [comment]
wkhtmltopdf enable to execute Ajax Requests, if you want to print dynamic page ti pdf, make you scripts able to get data from var's declared on page

**Comment by webgio** [comment]
@akonyer javascript should be executed by default and it will wait 200 msec. If you need more time you can set the --javascript-delay <msec> switch via the CustomSwitches property. Use the latest source code or nuget beta package (Install-Package Rotativa -Pre), since previous version ignored --javascript-delay <msec> switch. Also if page is doing ajax request, be careful to define the url as absolute url.

**Comment by akonyer** [comment]
I think the url's are generated using @Url.Action(), so I'll change them to be absolute strings. That could be my issue.

I'll check and get back to you soon.

Thanks

**Comment by akonyer** [comment]
I tried changing the url's to absolute urls from Url.Action, and I'm getting the same behavior. URL.Action.

ActionAsPdf works jsut fine, and all of the javascript executes. While ViewAsPdf does not seem to execute any javascript.

I'm using:  CustomSwitches = " --debug-javascript --no-stop-slow-scripts --javascript-delay 10000 "

**Comment by webgio** [comment]
What Rotativa version are you using?

**Comment by akonyer** [comment]
I just pulled your latest version from git, as I'm adding a content-disposition flag for inline/attachment.

The only reason I want to use ViewAsPdf instead of Action is to get around authorization -  as ActionAsPdf is anonymous. 

If it helps, I'm using knockout.js to populate data on the page with json data over ajax.

If you want, I can add a new *broken* test method when I toss you a pull request

**Comment by webgio** [comment]
@akonyer yes, a broken test would really help. please add it, thanks.

**Comment by webgio** [comment]
I think the problem is about cross domain requests, since wkhtmltopdf executes the page from local file system. To solve this you can use absolute url and allow cross domain requests on web.config, to do so add:

```xml
<system.webServer>

    <httpProtocol>
      <customHeaders>
        <clear />
        <add name="Access-Control-Allow-Origin" value="*" />
      </customHeaders>
    </httpProtocol>
```

**Comment by TimothyTateONE** [comment]
I have version 1.7.4-rc and am experiencing the same thing: the java script is not being executed after being deployed.  I tried the fix above, and it did not work
