### ISSUE TITLE
Rotativa doesn't work when published to Windows Azure.

### ISSUE THREAD

**Issue by projectzerotohero** [webgio/Rotativa#87]
I have a web app developed in Asp.net mvc 5 and I used rotativa for the pdf, It seems that rotativa doesn't work when published to Windows Azure but it works on my local machine.

Thanks.

**Comment by webgio** [comment]
It does work on Azure cloud service or VM. it doesn't work on Azure WebSites due to restrictions on executing external processes.

**Comment by projectzerotohero** [comment]
I see. Thanks.

**Comment by webgio** [comment]
I developed a service with the same Rotativa usage but you can use without having to worry about installing executables and having special permissions, so it will work with azure websites or shared hosting accounts. It's online at http://rotativahq.com
