### ISSUE TITLE
No Documentation Regarding the need for VC++ 2013 Runtime Installation

### ISSUE THREAD

**Issue by smdpersonal** [webgio/Rotativa#92]
Hello!

We recently came across an issue where generating worked fine until we deployed to our QA environment.  After some searching, we found a blurb in a forum mentioning that the VC++ 2013 Runtime is required.  We tried this and it worked.  Great! Now we're back on track.

The reason I'm creating this issue is to request that this be mentioned in the documentation for the project.  Understanding full requirements before use is important.

**Comment by webgio** [comment]
Please, consider submitting a pull request with the necessary additions to the Readme file.

Thanks,
Giorgio

Inviato da iPad
