### ISSUE TITLE
Is there a recommendation for how to run Rotativa from a background thread?

### ISSUE THREAD

**Issue by adrianwright** [webgio/Rotativa#93]
I have a request to send the PDF by email from a background thread, instead of serving to a browser.  The background thread is used due to the long wait time in generating the data for the PDF.

Is there a recommended way to do this, as ControllerContext will be lost in the background thread?

**Comment by hubert17** [comment]
This maybe unreliable, https://github.com/StephenCleary/AspNetBackgroundTasks 
It's Fire and Forget but you can create a log to not totally forget by checking whether task has been done or not.

**Comment by webgio** [comment]
An old issue, but I comment anyway... I guess those scenarios are better handled with a queue and a service consuming it. If on Azure then Azure queues and webjobs are really easy to use.
