### ISSUE TITLE
HTTP Error 401.2 - Unauthorized You are not authorized to view this page due to invalid authentication headers.

### ISSUE THREAD

**Issue by dawie** [webgio/Rotativa#94]
My View works fine, go to it in the browser.

When I pass the same View to ActionAsPdf, I get the following error:
HTTP Error 401.2 - Unauthorized You are not authorized to view this page due to invalid authentication headers.

**Comment by kbsaravana** [comment]
im also facing the same issue, 
have you resolved that issue?

**Comment by mianadil** [comment]
Same problem

**Comment by webgio** [comment]
ActionAsPdf needs page to be either public or athetocated with standard aspx auth. If not standard cookie auth then cookie name can be specified with the FormsAuthenticationCookieName parameter.
