### ISSUE TITLE
TrafficCop, $.get and ajax javascript requests always fail when view loads

### ISSUE THREAD

**Issue by jasonnelsoneg** [webgio/Rotativa#95]
I am trying to convert a MVC View to PDF.  When I call Rotativa.ViewAsPdf, I have javascript in my view that makes a call to trafficcop to get a handlebars template (Controller/Action that returns html)...but the request always fails.  I have tried even using $.get or ajax request and it always fails. My controller action for the handlebars template is set to AllowAnonymous.  Any ideas how to debug this or suggestions to get the trafficcop request to download the html template for the View?

**Comment by webgio** [comment]
I guess this could be related to wkhtmltopdf. Anyway I can't undersand why using something like TrafficCop in a PDF.
