### ISSUE TITLE
ActionAsPdf not calling method.

### ISSUE THREAD

**Issue by bkbartonDesign** [webgio/Rotativa#98]
When trying to access the ActionAsPdf function after an ActionResult, the method I am trying to access to gather data and to pass data to view does not get called. When I am debugging, the ActionPDF method gets called and a PDF is returned with an error saying that "Access is denied".

**Call from HTML**

```
<a href="@Url.Action("ActionPDF")" class="btn btn-outline">Export</a>
```

**Controller**

```
public ActionResult ActionPDF()
{

    return new Rotativa.ActionAsPdf("CreatePDF") { FileName = "ActionPDF.pdf" };

}

-----

public ActionResult CreatePDF()
{
    SessionModel sessionModel = CreateSession();

    NEHViewModel viewModel = new NEHViewModel(sessionModel);
    viewModel.LoadNEHModel(Id, Location);
    viewModel.LoadChartSettings();
    return View("Index", viewModel);
}

```

**Comment by webgio** [comment]
More then two years later, I hope you were able to find the bug. Just setting a breakpoint should have let you find it out.
